[workspace]
members = [
    "xtask",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.75"
mlua = { version = "0.9.1", features = ["luajit"] }

[package]
name = "vlur"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
mlua = { workspace = true, features = ["module", "macros"] }
walkdir = "2.4.0"
hashbrown = { version = "0.14.2", features = ["rkyv"] }
rkyv = "0.7.42"

[build-dependencies]
anyhow.workspace = true
mlua = { workspace = true, features = ["vendored"] }

[profile.release]
lto = true
codegen-units = 1
