[package]
name = "xtask"
version = "0.0.0"
edition.workspace = true

[[bin]]
name = "xtask"
path = "main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4.4.16", features = ["derive"] }
cargo_metadata = "0.18.1"
