name: Auto Fix

on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "**.lua"
      - ".rustfmt.toml"
      - ".stylua.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup cache for Rust
        uses: Swatinem/rust-cache@v2

      - name: Fix Rust code
        run: |
          rustup component add rustfmt clippy
          cargo clippy --workspace --fix --allow-dirty
          cargo fmt

      - name: Fix Lua code
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: ./lua

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: apply formatter/linter changes"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
