name: Fix

on:
  push:
    # branches:
    #   - main

env:
  CARGO_TERM_COLOR: always

jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Format Rust code
        run: |
          rustup component add rustfmt clippy
          cargo clippy --package=* --fix --allow-dirty
          cargo fmt

      - name: Format Lua code
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: ./lua

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: apply formatter/linter changes"
